name: "SnorlaxLOG"
version: '${project.version}'
main: de.snorlaxlog.bukkit.LOGLaxAPI
api-version: '1.20'
authors: [vazyx]
website: https://www.relaxogames.de
commands:
  warpui:
    description: Opens the Warp Inventory
  debug:
    description: DEBUG