name: "SnorlaxLOG"
version: '${project.version}'
main: de.snorlaxlog.bukkit.LOGLaxAPI
api-version: '1.20'
authors: [vazyx]
website: http://www.relaxogames.de
loadbefore:
  - SnorlaxLobby-V3
commands:
  warpui:
    description: Opens the Warp Inventory
  debug:
    description: DEBUG