name: "SnorlaxLOG"
version: '${project.version}'
main: de.relaxogames.snorlaxlog.bukkit.LOGLaxAPI
api-version: '1.20'
authors: [ "RelaxoGames Development Team" ]
website: https://www.relaxogames.de
commands:
  warpui:
    description: Opens the Warp Inventory
  debug:
    description: DEBUG