name: Build and Deploy Javadoc

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - run: javadoc -sourcepath ./src -d ./docs -subpackages main.java
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: docs
          folder: docs